### ISSUE TITLE
Latest Raspbian Image Upgrade not prompting

### ISSUE THREAD

**Issue by GuinnessStoutly** [davidferguson/pibakery-raspbian#22]
Raspbian has release an updated image since end of November, but when PiBarkery is launched it never issues a prompt to Upgrade the Raspbian image to the latest version.  Is it possible to manually do an update?

**Comment by davidferguson** [comment]
Very sorry for the delay; an update has now been released. Future updates will be faster.

In the next version of PiBakery (which I'm currently writing), you'll be able to choose any .img file on your computer to use, instead of being restricted to the ones I release.
