### ISSUE TITLE
Not Compatible with new Pi Zero W model

### ISSUE THREAD

**Issue by ashleycawley** [davidferguson/pibakery-raspbian#30]
With the release of the new **Pi Zero W model** (with WiFi & Bluetooth built in) a new Raspbian Lite image has to be used **or the system will not boot** (New image release date: 2017-03-02). This renders PiBakery currently non-functional with the latest Pi Zero W hardware sadly.

I love PiBakery and recommend it widely, however I believe that we need to see a better mechanism for it to identify if a new release is available and for it to offer to download it if required. I understand that whilst some features may change image to image the core features (like services) that PiBakery relies upon to function at boot hopefully will not change.

For this reason it might be wise to introduction two things:
1) The ability to identify a new release is available and to offer to download on the users behalf
2) The ability for the user to supply their own Raspbian image and for PiBakery to perform a best-effort integration in to that image.

Thank you for all the time and effort that is spent on this project, if I can be of any assistance at all please let me know.

**Comment by battletux** [comment]
I think the ability to supply your own image would be a good feature. It would rule out any lag between the foundation releasing a new distro for new hardware and Pi Bakery mirroring the change.

**Comment by davidferguson** [comment]
> I think the ability to supply your own image would be a good feature. It would rule out any lag between the foundation releasing a new distro for new hardware and Pi Bakery mirroring the change.

This is the future direction of PiBakery, and the new version of the app (which I'm currently working on) will have this feature.

However, for the moment I'm just uploading the new pibakery-raspbian modified release now, and will push that out as an update later today, if everything goes well.
