### ISSUE TITLE
Can't get a Raspberry PI Zero W to complete a silent install successfully

### ISSUE THREAD

**Issue by raiderj** [davidferguson/pibakery-raspbian#31]
I'm attempting to make a new rpi0-w work with a minimal configuration. Using a PiBakery script, I have the following blocks:

1. On First Boot
2. Set Hostname to "rpi0w"
3. Setup wifi
4. Reboot

So far I'm not able to see anything or access the Pi via SSH. Am I missing anything?

* When I look at the "wifiConnect.py" file on the uSD card, I don't see the setting I put into PiBakery. Maybe the block isn't setting wifi properly?
EDIT: I see that the boot script includes the variables, so they wouldn't be in the wifiConnect.py script. Still no luck getting this to work. The process should be the same between an RPI3 and Zero W, since the wifi/BT chip is the same?

**Comment by davidferguson** [comment]
The `wifiConnect.py` file won't have your settings in it - those are stored in the `firstBoot.sh` file, and passed in as command line arguments to the `wifiConnect.py` file.

- What version of PiBakery are you running? You should see the version number displayed briefly when PiBakery starts up.
- Are you using Windows or Mac?
- Raspbian Full, or Raspbian Lite?

In the `PiBakery` folder on the SD card (once you've run it in a Pi), there should be a `firstboot.log` file. Could you copy and paste the contents of that file here?

**Comment by raiderj** [comment]
I'll verify later today on the version, but it's what I downloaded this morning. Using Windows and writing Raspbian Lite. Will grab the file later too. I think when I checked it only had a few lines in that file.

**Comment by raiderj** [comment]
I'm using version 0.3.4.

Contents of the firstboot.log file:
`Selected interface 'wlan0'
OK`

**Comment by raiderj** [comment]
Closing - verified that PiBakery can be using on Windows 10 x64 to create a headless install for a Raspberry Pi Zero W. Just make sure to use a 2.4GHz wifi AP. Upon boot, I could see the new hostname in my router, and shortly thereafter putty in over port 22 and log in with default credentials.
