### ISSUE TITLE
Update button on modifying existing card doesn't do anything

### ISSUE THREAD

**Issue by dannystaple** [davidferguson/pibakery-raspbian#32]
If I insert a card that was previously prepared with PiBakery, it asks if I wish to modify the configuration.

If I then click yes, change some blocks in every boot (first boot has gone since it has been booted), then click "Update" - nothing happens, the new block XML is not written.

**Comment by davidferguson** [comment]
Are you on Windows or Mac?

If you use the keyboard shortcut `CTRL - SHIFT - I` on Windows or `CMD - SHIFT - I` on Mac, you'll get another window opening. Would you be able to select the `Console` tab at the top, and then upload a screenshot of that window here?

**Comment by dannystaple** [comment]
Screenshot here (along with the relevant folder on the microsd)

![2017-03-22 2](https://cloud.githubusercontent.com/assets/426859/24219909/5dd76d98-0f40-11e7-837f-e7bc8827e5ec.png)

**Comment by dannystaple** [comment]
Sorry - I ingeniously hid the full error messages behind the explorer screen - trying that again...

![2017-03-22 4](https://cloud.githubusercontent.com/assets/426859/24220009/b1677e08-0f40-11e7-9548-fd53b48bfecc.png)

**Comment by davidferguson** [comment]
It looks like you may have the write protect switch on the SD card set - can you check this?

**Comment by dannystaple** [comment]
Argg - I feel pretty daft now - I had done exactly that at some point, and din't think to check it. It's not the same issue, but perhaps a suggestion when it can't write to check that would be pretty awesome.

**Comment by davidferguson** [comment]
Don't worry - I think every Raspberry Pi user has done that at some point, myself included (many times).

In the next release I'll include a message that suggests they check the write protect switch.

**Comment by polygonfuture** [comment]
This thread should not be closed.

There is still a bug with the way your code is searching for the drive letters.
``
![piblocks_bad](https://cloud.githubusercontent.com/assets/12026545/26821311/d7126c4e-4a5a-11e7-87a3-d0caf6f45af6.PNG)
