### ISSUE TITLE
Site Download

### ISSUE THREAD

**Issue by maniflames** [davidferguson/pibakery-raspbian#42]
Hi, 

I tried to download the Pi Backery installer (windows) from the site but it keeps failing. 
I'll probably figure out how to accomplish what I want from the github repo but I just wanted to let you know. 

Thanks for building this anyway!
 I'm pretty excited to try it out :)

**Comment by davidferguson** [comment]
Hi,
I'm sorry you're having issues, the downloads are hosted on GitHub and they seem to be failing a lot at the moment.

I've put up a temporary mirror of the Windows installer at http://pibakery.org/downloads/ - please let me know if this works for you.

David

**Comment by maniflames** [comment]
The downoad totally worked 🎉 
Thank you so much :)
