### ISSUE TITLE
Stretch

### ISSUE THREAD

**Issue by loranger** [davidferguson/pibakery-raspbian#46]
As reported in the issue davidferguson/pibakery/issues/112, it would be great to use raspbian stretch instead of raspbian jessie

**Comment by PeterChauYEG** [comment]
Hi,

I was able to get Raspbian Stretch by adding the image to the os folder as specified in the 'build from source' [instructions](https://github.com/davidferguson/pibakery/).

Here's my config in images.json:
```
[
	{
		"compressedFilename": "2017-11-29-raspbian-stretch.zip",
		"compressedMD5": "e7b86f2f0e8654ae47d0f051cdb5bdfe",
		"displayName": "Raspbian Full - Stretch",
		"downloadUrl": "https://downloads.raspberrypi.org/raspbian_latest",
		"filename": "2017-11-29-raspbian-stretch.img",
		"installed": false,
		"skipVersion": 0,
		"uncompressedFilename": "2017-11-29-raspbian-stretch.img",
		"uncompressedMD5": "8fdf6c6c4a3aaa263cfc3912d43a46e2",
		"uncompressedSize": 4919918592,
		"version": 4.9
	}
]
```

What OS are you on? I haven't tried but when I open up the MacOS binary, I see that I can add additional OS' there. I'd assume the same is true for windows.

https://github.com/davidferguson/pibakery/issues/112

note to future me: get MD5s with `openssl md5 <file>`.

**Comment by davidferguson** [comment]
You can't just add in the images from the Pi Foundation in - they won't work. The images PiBakery uses are very slightly customised to work with PiBakery, the files modified are shown in this repository.

Apologies for the massive and unacceptable delay in updating to Stretch - a combination of uni, exams and Stretch breaking quite a few things caused this.

I do have what I *think* are working Stretch images ready now, and hope to push them out very soon. Just a little bit more testing - but PiBakery should be on Stretch before the end of 2017.

**Comment by loranger** [comment]
Thank you so much !
