### ISSUE TITLE
Sandbox violation when writing to SD card with Mac

### ISSUE THREAD

**Issue by domwakeling** [davidferguson/pibakery-raspbian#47]
Using PiBakery on a Mac running Sierra (10.12.16), when trying to write to a card the "Write to SD Card" modal's progress bar fills but never completes.

I'm seeing repeated messages in the logs warning of a sandbox violation, eg:

`SandboxViolation: diskutil(18883) System Policy: deny file-ioctl /dev/rdisk0
Violation:       System Policy: deny file-ioctl /dev/rdisk0 
Process:         diskutil [18883]
Path:            /usr/sbin/diskutil
Load Address:    0x109d10000
Identifier:      diskutil
Version:         ??? (???)
Code Type:       x86_64 (Native)
Parent Process:  bash [18873]
Responsible:     /Applications/PiBakery.app/Contents/MacOS/PiBakery [16815]
User ID:         0
`

Not sure how long it's been since I used PiBakery (a few months) or which version of MacOS I was running at the time (probably an earlier version of Sierra) but not had this issue previously.

**Comment by davidferguson** [comment]
I've definitely had PiBakery running fine on Sierra before. I don't currently have Sierra installed but I'm re-downloading the installer so I should be able to do a few tests in the upcoming days.

**Comment by domwakeling** [comment]
If it helps - the card was written with a working OS, but without any of the PiBakery 'extras'.
