### ISSUE TITLE
don't run #!/usr/bin/env (command)

### ISSUE THREAD

**Issue by japharl** [davidferguson/pibakery-raspbian#5]
#!/usr/bin/env (command) is bad for security purposes.  Instead, explicitly state the path (such as /bin/bash ) as you may unintentionally nuke a system.  (Saw this in your blocks documentation.)

**Comment by davidferguson** [comment]
Thanks - I didn't know that. Fixed on the docs, and I'll correct the actual block files shortly.

**Comment by davidferguson** [comment]
I've now updated this in the block files, and plan to push out a block update this weekend which will contain this fix.

Thanks for helping with and using PiBakery!
