### ISSUE TITLE
Installer don´t finish on Xubuntu 16.04

### ISSUE THREAD

**Issue by malliwi88** [davidferguson/pibakery-raspbian#6]
Always wait in "Attempt Auto-Fix" process.

**Comment by davidferguson** [comment]
I have a feeling I know what's causing this and I'll investigate, but in the meantime you can manually download the customised version of raspbian from the [releases page](https://github.com/davidferguson/pibakery-raspbian/releases) and extract the .7z file into the `os/` directory.

I have to warn you however that PiBakery doesn't work on Linux yet - although a version that does is nearly ready and should be released in a few days.

**Comment by davidferguson** [comment]
The [pibakery source](https://github.com/davidferguson/pibakery) has now been updated to support linux, so if you build from source it should work fine now. See the [instructions in the readme](https://github.com/davidferguson/pibakery/blob/master/README.md#installing-from-source) on how to build from source.

I'm planning on releasing .deb and .rpm packages for PiBakery this weekend.
