### ISSUE TITLE
Installing LAMP

### ISSUE THREAD

**Issue by hawkesley** [davidferguson/pibakery-raspbian#7]
Can you let me know what passwords and users are set for Mysql.
I want to use Phpmyadmin but tyring to log into Mysql with root and root does not work (root being the password set on installing phpmyadmin.
Thank you for your help and a great way to set up an SD.

mike stocks

pS Adding PHPmyadmin would be a great addition.

**Comment by davidferguson** [comment]
I don't have my Raspberry Pi on hand to test, but I believe it should be set to blank. To test, run `mysql -u root -p` on the command line, and leave the password blank when it asks for one.

**Comment by hawkesley** [comment]
Hi David,Thanks for coming back. That works for mysql, but not for the log in for phpmyadmin. I get login without a password is not allowed.If I use root and root I get 1045 error cant log into mysql.I presume I will have to modify the phpmyadmin config.Any comments appreciated.best regards,
mike
 

    On Wednesday, 14 September 2016, 14:26, David Ferguson <notifications@github.com> wrote:
 

 I don't have my Raspberry Pi on hand to test, but I believe it should be set to blank. To test, run mysql -u root -p on the command line, and leave the password blank when it asks for one.—

**Comment by davidferguson** [comment]
I don't use PHPmyAdmin, so I'm not sure about this, but can you try running the command
`mysqladmin -u root password mynewpassword` where `mynewpassword` can be any password of your choice.

Then try logging in with PHPmyAdmin with the username `root` and the password whatever you set it to, to see if that works. If that does, I'll change the `Install LAMP` block to include a field for the MySQL password so you can set it during the PiBakery stage.

**Comment by hawkesley** [comment]
Hi David,Yes that worked. Thank you.Since passwords are always a pain if you forget them, maybe a script that captured the passwords entered on the build and displayed / stored them on the PI.Not a secure method probably.Have a good day.mike 

    On Thursday, 15 September 2016, 11:21, David Ferguson <notifications@github.com> wrote:
 

 I don't use PHPmyAdmin, so I'm not sure about this, but can you try running the command
mysqladmin -u root password mynewpassword where mynewpassword can be any password of your choice.Then try logging in with PHPmyAdmin with the username root and the password whatever you set it to, to see if that works. If that does, I'll change the Install LAMP block to include a field for the MySQL password so you can set it during the PiBakery stage.—

**Comment by davidferguson** [comment]
I'll update the Install LAMP block so that there's a field for the MySQL password to be entered straight into the block. This way you users won't have to run that command to set a password.

**Comment by davidferguson** [comment]
It's now in the [pibakery-blocks repo](https://github.com/davidferguson/pibakery-blocks), and I'll try and push out block update which includes it within the next few days.

**Comment by hawkesley** [comment]
Well done and thanks
Mike
