### ISSUE TITLE
Add an option to view commands as they are executed...

### ISSUE THREAD

**Issue by japharl** [davidferguson/pibakery-raspbian#8]
Add an option to view commands as they are executed (rather than the percentage window) to allow for debugging.  Specifically, I would like to know if commands like apt-get update would fail on first boot.

**Comment by davidferguson** [comment]
I probably won't add this, as it might confuse users who don't understand what their Pi is doing - but I'm happy to have PiBakery log all output to a file - would that do?

**Comment by japharl** [comment]
That would work great.

**Comment by davidferguson** [comment]
If you build PiBakery [from source](https://github.com/davidferguson/pibakery) the logging should be enabled now, into the folder `/boot/PiBakery/` with the names `firstBoot.log`, `everyBoot.log` and `nextBoot.log`. I'm planning on updating the installers either today or tomorrow, and logging will get added in to them when I do that.

**Comment by LowPowerLab** [comment]
+1 to actually displaying more than just the percent and type of command being executed.
Would be very useful to see what command fails in real time.
